env: TRAVIS_CI=true

language: node_js
node_js:
  - 6

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: node_modules/karma/bin/karma start karma.conf.js

cache:
  directories:
    - node_modules
